name: PostgreSQL service example
on: push

jobs:
  # Service containers to run with `container-job`
  test:
    name: Test
    runs-on: ubuntu-last

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: golang-server
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          APP_DB_USERNAME: "postgres"
          APP_DB_PASSWORD: "password"
          APP_DB_NAME: "golang-server"
          file_name: .env

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        # env:
        #   APP_DB_USERNAME: postgres
        #   APP_DB_PASSWORD: password
        #   APP_DB_NAME: postgres
