name: PostgreSQL service example
on: push

jobs:
    create-envfile:

        runs-on: ubuntu-latest
          
        steps:
        - name: Make envfile
          uses: go-server/create-envfile@v1
          with:
            APP_DB_USERNAME: postgres
            APP_DB_PASSWORD: password
            APP_DB_NAME: postgres
            file_name: .env
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

    #   - name: Connect to PostgreSQL
    #     uses: go-server/create-envfile@1
    #     with:
    #       APP_DB_USERNAME: postgres
    #       APP_DB_PASSWORD: password
    #       APP_DB_NAME: postgres
